// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

package com.reworld.www;

public final class Teamwork {
  private Teamwork() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PersonReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PersonReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>string id_card = 2;</code>
     */
    java.lang.String getIdCard();
    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>string id_card = 2;</code>
     */
    com.google.protobuf.ByteString
        getIdCardBytes();

    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 3;</code>
     */
    int getAge();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.PersonReply.Sex sex = 4;</code>
     */
    int getSexValue();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.PersonReply.Sex sex = 4;</code>
     */
    com.reworld.www.Teamwork.PersonReply.Sex getSex();

    /**
     * <pre>
     *是否已婚
     * </pre>
     *
     * <code>bool married = 5;</code>
     */
    boolean getMarried();

    /**
     * <pre>
     *资产
     * </pre>
     *
     * <code>double amount = 6;</code>
     */
    double getAmount();

    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    java.util.List<java.lang.String>
        getAddressList();
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    int getAddressCount();
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    java.lang.String getAddress(int index);
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    com.google.protobuf.ByteString
        getAddressBytes(int index);

    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    java.util.List<com.google.protobuf.Any> 
        getOthersList();
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    com.google.protobuf.Any getOthers(int index);
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    int getOthersCount();
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getOthersOrBuilderList();
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    com.google.protobuf.AnyOrBuilder getOthersOrBuilder(
        int index);

    /**
     * <code>bytes data = 10;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * 相应结果
   * </pre>
   *
   * Protobuf type {@code PersonReply}
   */
  public  static final class PersonReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PersonReply)
      PersonReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PersonReply.newBuilder() to construct.
    private PersonReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PersonReply() {
      name_ = "";
      idCard_ = "";
      sex_ = 0;
      address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      others_ = java.util.Collections.emptyList();
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PersonReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PersonReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              idCard_ = s;
              break;
            }
            case 24: {

              age_ = input.readInt32();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
            case 40: {

              married_ = input.readBool();
              break;
            }
            case 49: {

              amount_ = input.readDouble();
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                address_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              address_.add(s);
              break;
            }
            case 74: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                others_ = new java.util.ArrayList<com.google.protobuf.Any>();
                mutable_bitField0_ |= 0x00000002;
              }
              others_.add(
                  input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry));
              break;
            }
            case 82: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          address_ = address_.getUnmodifiableView();
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          others_ = java.util.Collections.unmodifiableList(others_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reworld.www.Teamwork.internal_static_PersonReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reworld.www.Teamwork.internal_static_PersonReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reworld.www.Teamwork.PersonReply.class, com.reworld.www.Teamwork.PersonReply.Builder.class);
    }

    /**
     * Protobuf enum {@code PersonReply.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FEMALE = 0;</code>
       */
      FEMALE(0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FEMALE = 0;</code>
       */
      public static final int FEMALE_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return FEMALE;
          case 1: return MALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.reworld.www.Teamwork.PersonReply.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:PersonReply.Sex)
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_CARD_FIELD_NUMBER = 2;
    private volatile java.lang.Object idCard_;
    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>string id_card = 2;</code>
     */
    public java.lang.String getIdCard() {
      java.lang.Object ref = idCard_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idCard_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *身份证
     * </pre>
     *
     * <code>string id_card = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIdCardBytes() {
      java.lang.Object ref = idCard_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idCard_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 3;
    private int age_;
    /**
     * <pre>
     *年龄
     * </pre>
     *
     * <code>int32 age = 3;</code>
     */
    public int getAge() {
      return age_;
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.PersonReply.Sex sex = 4;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.PersonReply.Sex sex = 4;</code>
     */
    public com.reworld.www.Teamwork.PersonReply.Sex getSex() {
      @SuppressWarnings("deprecation")
      com.reworld.www.Teamwork.PersonReply.Sex result = com.reworld.www.Teamwork.PersonReply.Sex.valueOf(sex_);
      return result == null ? com.reworld.www.Teamwork.PersonReply.Sex.UNRECOGNIZED : result;
    }

    public static final int MARRIED_FIELD_NUMBER = 5;
    private boolean married_;
    /**
     * <pre>
     *是否已婚
     * </pre>
     *
     * <code>bool married = 5;</code>
     */
    public boolean getMarried() {
      return married_;
    }

    public static final int AMOUNT_FIELD_NUMBER = 6;
    private double amount_;
    /**
     * <pre>
     *资产
     * </pre>
     *
     * <code>double amount = 6;</code>
     */
    public double getAmount() {
      return amount_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 7;
    private com.google.protobuf.LazyStringList address_;
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAddressList() {
      return address_;
    }
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    public int getAddressCount() {
      return address_.size();
    }
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    public java.lang.String getAddress(int index) {
      return address_.get(index);
    }
    /**
     * <pre>
     *地址
     * </pre>
     *
     * <code>repeated string address = 7;</code>
     */
    public com.google.protobuf.ByteString
        getAddressBytes(int index) {
      return address_.getByteString(index);
    }

    public static final int OTHERS_FIELD_NUMBER = 9;
    private java.util.List<com.google.protobuf.Any> others_;
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    public java.util.List<com.google.protobuf.Any> getOthersList() {
      return others_;
    }
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
        getOthersOrBuilderList() {
      return others_;
    }
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    public int getOthersCount() {
      return others_.size();
    }
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    public com.google.protobuf.Any getOthers(int index) {
      return others_.get(index);
    }
    /**
     * <pre>
     *其他
     * </pre>
     *
     * <code>repeated .google.protobuf.Any Others = 9;</code>
     */
    public com.google.protobuf.AnyOrBuilder getOthersOrBuilder(
        int index) {
      return others_.get(index);
    }

    public static final int DATA_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>bytes data = 10;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getIdCardBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, idCard_);
      }
      if (age_ != 0) {
        output.writeInt32(3, age_);
      }
      if (sex_ != com.reworld.www.Teamwork.PersonReply.Sex.FEMALE.getNumber()) {
        output.writeEnum(4, sex_);
      }
      if (married_ != false) {
        output.writeBool(5, married_);
      }
      if (amount_ != 0D) {
        output.writeDouble(6, amount_);
      }
      for (int i = 0; i < address_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, address_.getRaw(i));
      }
      for (int i = 0; i < others_.size(); i++) {
        output.writeMessage(9, others_.get(i));
      }
      if (!data_.isEmpty()) {
        output.writeBytes(10, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getIdCardBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, idCard_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, age_);
      }
      if (sex_ != com.reworld.www.Teamwork.PersonReply.Sex.FEMALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sex_);
      }
      if (married_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, married_);
      }
      if (amount_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, amount_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < address_.size(); i++) {
          dataSize += computeStringSizeNoTag(address_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getAddressList().size();
      }
      for (int i = 0; i < others_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, others_.get(i));
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reworld.www.Teamwork.PersonReply)) {
        return super.equals(obj);
      }
      com.reworld.www.Teamwork.PersonReply other = (com.reworld.www.Teamwork.PersonReply) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getIdCard()
          .equals(other.getIdCard())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (sex_ != other.sex_) return false;
      if (getMarried()
          != other.getMarried()) return false;
      if (java.lang.Double.doubleToLongBits(getAmount())
          != java.lang.Double.doubleToLongBits(
              other.getAmount())) return false;
      if (!getAddressList()
          .equals(other.getAddressList())) return false;
      if (!getOthersList()
          .equals(other.getOthersList())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_CARD_FIELD_NUMBER;
      hash = (53 * hash) + getIdCard().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      hash = (37 * hash) + MARRIED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMarried());
      hash = (37 * hash) + AMOUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmount()));
      if (getAddressCount() > 0) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddressList().hashCode();
      }
      if (getOthersCount() > 0) {
        hash = (37 * hash) + OTHERS_FIELD_NUMBER;
        hash = (53 * hash) + getOthersList().hashCode();
      }
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.PersonReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.PersonReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.PersonReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reworld.www.Teamwork.PersonReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 相应结果
     * </pre>
     *
     * Protobuf type {@code PersonReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PersonReply)
        com.reworld.www.Teamwork.PersonReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reworld.www.Teamwork.internal_static_PersonReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reworld.www.Teamwork.internal_static_PersonReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reworld.www.Teamwork.PersonReply.class, com.reworld.www.Teamwork.PersonReply.Builder.class);
      }

      // Construct using com.reworld.www.Teamwork.PersonReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getOthersFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        idCard_ = "";

        age_ = 0;

        sex_ = 0;

        married_ = false;

        amount_ = 0D;

        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (othersBuilder_ == null) {
          others_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          othersBuilder_.clear();
        }
        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reworld.www.Teamwork.internal_static_PersonReply_descriptor;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.PersonReply getDefaultInstanceForType() {
        return com.reworld.www.Teamwork.PersonReply.getDefaultInstance();
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.PersonReply build() {
        com.reworld.www.Teamwork.PersonReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.PersonReply buildPartial() {
        com.reworld.www.Teamwork.PersonReply result = new com.reworld.www.Teamwork.PersonReply(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.idCard_ = idCard_;
        result.age_ = age_;
        result.sex_ = sex_;
        result.married_ = married_;
        result.amount_ = amount_;
        if (((bitField0_ & 0x00000001) != 0)) {
          address_ = address_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.address_ = address_;
        if (othersBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            others_ = java.util.Collections.unmodifiableList(others_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.others_ = others_;
        } else {
          result.others_ = othersBuilder_.build();
        }
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reworld.www.Teamwork.PersonReply) {
          return mergeFrom((com.reworld.www.Teamwork.PersonReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reworld.www.Teamwork.PersonReply other) {
        if (other == com.reworld.www.Teamwork.PersonReply.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getIdCard().isEmpty()) {
          idCard_ = other.idCard_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        if (other.getMarried() != false) {
          setMarried(other.getMarried());
        }
        if (other.getAmount() != 0D) {
          setAmount(other.getAmount());
        }
        if (!other.address_.isEmpty()) {
          if (address_.isEmpty()) {
            address_ = other.address_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAddressIsMutable();
            address_.addAll(other.address_);
          }
          onChanged();
        }
        if (othersBuilder_ == null) {
          if (!other.others_.isEmpty()) {
            if (others_.isEmpty()) {
              others_ = other.others_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureOthersIsMutable();
              others_.addAll(other.others_);
            }
            onChanged();
          }
        } else {
          if (!other.others_.isEmpty()) {
            if (othersBuilder_.isEmpty()) {
              othersBuilder_.dispose();
              othersBuilder_ = null;
              others_ = other.others_;
              bitField0_ = (bitField0_ & ~0x00000002);
              othersBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getOthersFieldBuilder() : null;
            } else {
              othersBuilder_.addAllMessages(other.others_);
            }
          }
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reworld.www.Teamwork.PersonReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reworld.www.Teamwork.PersonReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object idCard_ = "";
      /**
       * <pre>
       *身份证
       * </pre>
       *
       * <code>string id_card = 2;</code>
       */
      public java.lang.String getIdCard() {
        java.lang.Object ref = idCard_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          idCard_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *身份证
       * </pre>
       *
       * <code>string id_card = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIdCardBytes() {
        java.lang.Object ref = idCard_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          idCard_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *身份证
       * </pre>
       *
       * <code>string id_card = 2;</code>
       */
      public Builder setIdCard(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        idCard_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *身份证
       * </pre>
       *
       * <code>string id_card = 2;</code>
       */
      public Builder clearIdCard() {
        
        idCard_ = getDefaultInstance().getIdCard();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *身份证
       * </pre>
       *
       * <code>string id_card = 2;</code>
       */
      public Builder setIdCardBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        idCard_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       */
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *年龄
       * </pre>
       *
       * <code>int32 age = 3;</code>
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.PersonReply.Sex sex = 4;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.PersonReply.Sex sex = 4;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.PersonReply.Sex sex = 4;</code>
       */
      public com.reworld.www.Teamwork.PersonReply.Sex getSex() {
        @SuppressWarnings("deprecation")
        com.reworld.www.Teamwork.PersonReply.Sex result = com.reworld.www.Teamwork.PersonReply.Sex.valueOf(sex_);
        return result == null ? com.reworld.www.Teamwork.PersonReply.Sex.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.PersonReply.Sex sex = 4;</code>
       */
      public Builder setSex(com.reworld.www.Teamwork.PersonReply.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.PersonReply.Sex sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }

      private boolean married_ ;
      /**
       * <pre>
       *是否已婚
       * </pre>
       *
       * <code>bool married = 5;</code>
       */
      public boolean getMarried() {
        return married_;
      }
      /**
       * <pre>
       *是否已婚
       * </pre>
       *
       * <code>bool married = 5;</code>
       */
      public Builder setMarried(boolean value) {
        
        married_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *是否已婚
       * </pre>
       *
       * <code>bool married = 5;</code>
       */
      public Builder clearMarried() {
        
        married_ = false;
        onChanged();
        return this;
      }

      private double amount_ ;
      /**
       * <pre>
       *资产
       * </pre>
       *
       * <code>double amount = 6;</code>
       */
      public double getAmount() {
        return amount_;
      }
      /**
       * <pre>
       *资产
       * </pre>
       *
       * <code>double amount = 6;</code>
       */
      public Builder setAmount(double value) {
        
        amount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *资产
       * </pre>
       *
       * <code>double amount = 6;</code>
       */
      public Builder clearAmount() {
        
        amount_ = 0D;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureAddressIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          address_ = new com.google.protobuf.LazyStringArrayList(address_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getAddressList() {
        return address_.getUnmodifiableView();
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public int getAddressCount() {
        return address_.size();
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public java.lang.String getAddress(int index) {
        return address_.get(index);
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public com.google.protobuf.ByteString
          getAddressBytes(int index) {
        return address_.getByteString(index);
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public Builder setAddress(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public Builder addAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public Builder addAllAddress(
          java.lang.Iterable<java.lang.String> values) {
        ensureAddressIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, address_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public Builder clearAddress() {
        address_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *地址
       * </pre>
       *
       * <code>repeated string address = 7;</code>
       */
      public Builder addAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureAddressIsMutable();
        address_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<com.google.protobuf.Any> others_ =
        java.util.Collections.emptyList();
      private void ensureOthersIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          others_ = new java.util.ArrayList<com.google.protobuf.Any>(others_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> othersBuilder_;

      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public java.util.List<com.google.protobuf.Any> getOthersList() {
        if (othersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(others_);
        } else {
          return othersBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public int getOthersCount() {
        if (othersBuilder_ == null) {
          return others_.size();
        } else {
          return othersBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public com.google.protobuf.Any getOthers(int index) {
        if (othersBuilder_ == null) {
          return others_.get(index);
        } else {
          return othersBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder setOthers(
          int index, com.google.protobuf.Any value) {
        if (othersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthersIsMutable();
          others_.set(index, value);
          onChanged();
        } else {
          othersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder setOthers(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (othersBuilder_ == null) {
          ensureOthersIsMutable();
          others_.set(index, builderForValue.build());
          onChanged();
        } else {
          othersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder addOthers(com.google.protobuf.Any value) {
        if (othersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthersIsMutable();
          others_.add(value);
          onChanged();
        } else {
          othersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder addOthers(
          int index, com.google.protobuf.Any value) {
        if (othersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOthersIsMutable();
          others_.add(index, value);
          onChanged();
        } else {
          othersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder addOthers(
          com.google.protobuf.Any.Builder builderForValue) {
        if (othersBuilder_ == null) {
          ensureOthersIsMutable();
          others_.add(builderForValue.build());
          onChanged();
        } else {
          othersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder addOthers(
          int index, com.google.protobuf.Any.Builder builderForValue) {
        if (othersBuilder_ == null) {
          ensureOthersIsMutable();
          others_.add(index, builderForValue.build());
          onChanged();
        } else {
          othersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder addAllOthers(
          java.lang.Iterable<? extends com.google.protobuf.Any> values) {
        if (othersBuilder_ == null) {
          ensureOthersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, others_);
          onChanged();
        } else {
          othersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder clearOthers() {
        if (othersBuilder_ == null) {
          others_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          othersBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public Builder removeOthers(int index) {
        if (othersBuilder_ == null) {
          ensureOthersIsMutable();
          others_.remove(index);
          onChanged();
        } else {
          othersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public com.google.protobuf.Any.Builder getOthersBuilder(
          int index) {
        return getOthersFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public com.google.protobuf.AnyOrBuilder getOthersOrBuilder(
          int index) {
        if (othersBuilder_ == null) {
          return others_.get(index);  } else {
          return othersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public java.util.List<? extends com.google.protobuf.AnyOrBuilder> 
           getOthersOrBuilderList() {
        if (othersBuilder_ != null) {
          return othersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(others_);
        }
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public com.google.protobuf.Any.Builder addOthersBuilder() {
        return getOthersFieldBuilder().addBuilder(
            com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public com.google.protobuf.Any.Builder addOthersBuilder(
          int index) {
        return getOthersFieldBuilder().addBuilder(
            index, com.google.protobuf.Any.getDefaultInstance());
      }
      /**
       * <pre>
       *其他
       * </pre>
       *
       * <code>repeated .google.protobuf.Any Others = 9;</code>
       */
      public java.util.List<com.google.protobuf.Any.Builder> 
           getOthersBuilderList() {
        return getOthersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getOthersFieldBuilder() {
        if (othersBuilder_ == null) {
          othersBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  others_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          others_ = null;
        }
        return othersBuilder_;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 10;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 10;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 10;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PersonReply)
    }

    // @@protoc_insertion_point(class_scope:PersonReply)
    private static final com.reworld.www.Teamwork.PersonReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reworld.www.Teamwork.PersonReply();
    }

    public static com.reworld.www.Teamwork.PersonReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PersonReply>
        PARSER = new com.google.protobuf.AbstractParser<PersonReply>() {
      @java.lang.Override
      public PersonReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PersonReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PersonReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PersonReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.reworld.www.Teamwork.PersonReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PersonReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PersonReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016protocol.proto\032!include/google/protobu" +
      "f/any.proto\"\333\001\n\013PersonReply\022\014\n\004name\030\001 \001(" +
      "\t\022\017\n\007id_card\030\002 \001(\t\022\013\n\003age\030\003 \001(\005\022\035\n\003sex\030\004" +
      " \001(\0162\020.PersonReply.Sex\022\017\n\007married\030\005 \001(\010\022" +
      "\016\n\006amount\030\006 \001(\001\022\017\n\007address\030\007 \003(\t\022$\n\006Othe" +
      "rs\030\t \003(\0132\024.google.protobuf.Any\022\014\n\004data\030\n" +
      " \001(\014\"\033\n\003Sex\022\n\n\006FEMALE\020\000\022\010\n\004MALE\020\001B4\n\017com" +
      ".reworld.wwwB\010TeamworkZ\004.;pb\252\002\020Reworld.T" +
      "eamworkb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_PersonReply_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PersonReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PersonReply_descriptor,
        new java.lang.String[] { "Name", "IdCard", "Age", "Sex", "Married", "Amount", "Address", "Others", "Data", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
