// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: response.proto

package com.reworld.www;

public final class Teamwork {
  private Teamwork() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 服务端响应操作类型
   * </pre>
   *
   * Protobuf enum {@code PongAction}
   */
  public enum PongAction
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 成员上线通知(带有染色等状态数据)
     * </pre>
     *
     * <code>OnlineNotice = 0;</code>
     */
    OnlineNotice(0),
    /**
     * <pre>
     * 成员(主动)下线通知
     * </pre>
     *
     * <code>OfflineNotice = 1;</code>
     */
    OfflineNotice(1),
    /**
     * <pre>
     * 地图分发数据(透传) packet
     * </pre>
     *
     * <code>DataDistribute = 2;</code>
     */
    DataDistribute(2),
    /**
     * <pre>
     * 地图副本数据(透传)
     * </pre>
     *
     * <code>DataReplica = 3;</code>
     */
    DataReplica(3),
    /**
     * <pre>
     * 请求定时快照
     * </pre>
     *
     * <code>Snapshot = 4;</code>
     */
    Snapshot(4),
    /**
     * <pre>
     * 暂停编辑(通知)
     * </pre>
     *
     * <code>Hangup = 5;</code>
     */
    Hangup(5),
    /**
     * <pre>
     * 销毁项目(通知)
     * </pre>
     *
     * <code>Dispose = 6;</code>
     */
    Dispose(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 成员上线通知(带有染色等状态数据)
     * </pre>
     *
     * <code>OnlineNotice = 0;</code>
     */
    public static final int OnlineNotice_VALUE = 0;
    /**
     * <pre>
     * 成员(主动)下线通知
     * </pre>
     *
     * <code>OfflineNotice = 1;</code>
     */
    public static final int OfflineNotice_VALUE = 1;
    /**
     * <pre>
     * 地图分发数据(透传) packet
     * </pre>
     *
     * <code>DataDistribute = 2;</code>
     */
    public static final int DataDistribute_VALUE = 2;
    /**
     * <pre>
     * 地图副本数据(透传)
     * </pre>
     *
     * <code>DataReplica = 3;</code>
     */
    public static final int DataReplica_VALUE = 3;
    /**
     * <pre>
     * 请求定时快照
     * </pre>
     *
     * <code>Snapshot = 4;</code>
     */
    public static final int Snapshot_VALUE = 4;
    /**
     * <pre>
     * 暂停编辑(通知)
     * </pre>
     *
     * <code>Hangup = 5;</code>
     */
    public static final int Hangup_VALUE = 5;
    /**
     * <pre>
     * 销毁项目(通知)
     * </pre>
     *
     * <code>Dispose = 6;</code>
     */
    public static final int Dispose_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PongAction valueOf(int value) {
      return forNumber(value);
    }

    public static PongAction forNumber(int value) {
      switch (value) {
        case 0: return OnlineNotice;
        case 1: return OfflineNotice;
        case 2: return DataDistribute;
        case 3: return DataReplica;
        case 4: return Snapshot;
        case 5: return Hangup;
        case 6: return Dispose;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PongAction>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PongAction> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PongAction>() {
            public PongAction findValueByNumber(int number) {
              return PongAction.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.reworld.www.Teamwork.getDescriptor().getEnumTypes().get(0);
    }

    private static final PongAction[] VALUES = values();

    public static PongAction valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PongAction(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PongAction)
  }

  /**
   * Protobuf enum {@code PongCode}
   */
  public enum PongCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * 正常
     * </pre>
     *
     * <code>ok = 0;</code>
     */
    ok(0),
    /**
     * <pre>
     * 签名错误
     * </pre>
     *
     * <code>err_sign = 1;</code>
     */
    err_sign(1),
    /**
     * <pre>
     * 参数错误
     * </pre>
     *
     * <code>err_param = 2;</code>
     */
    err_param(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * 正常
     * </pre>
     *
     * <code>ok = 0;</code>
     */
    public static final int ok_VALUE = 0;
    /**
     * <pre>
     * 签名错误
     * </pre>
     *
     * <code>err_sign = 1;</code>
     */
    public static final int err_sign_VALUE = 1;
    /**
     * <pre>
     * 参数错误
     * </pre>
     *
     * <code>err_param = 2;</code>
     */
    public static final int err_param_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PongCode valueOf(int value) {
      return forNumber(value);
    }

    public static PongCode forNumber(int value) {
      switch (value) {
        case 0: return ok;
        case 1: return err_sign;
        case 2: return err_param;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PongCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PongCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PongCode>() {
            public PongCode findValueByNumber(int number) {
              return PongCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.reworld.www.Teamwork.getDescriptor().getEnumTypes().get(1);
    }

    private static final PongCode[] VALUES = values();

    public static PongCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PongCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:PongCode)
  }

  public interface MemberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Member)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 用户编号(OpenId)
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    java.lang.String getUUID();
    /**
     * <pre>
     * 用户编号(OpenId)
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    com.google.protobuf.ByteString
        getUUIDBytes();

    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 上线序列/染色(可选)
     * </pre>
     *
     * <code>fixed32 Sequence = 3;</code>
     */
    int getSequence();
  }
  /**
   * Protobuf type {@code Member}
   */
  public  static final class Member extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Member)
      MemberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Member.newBuilder() to construct.
    private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Member() {
      uUID_ = "";
      name_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Member();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Member(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uUID_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 29: {

              sequence_ = input.readFixed32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reworld.www.Teamwork.internal_static_Member_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reworld.www.Teamwork.internal_static_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reworld.www.Teamwork.Member.class, com.reworld.www.Teamwork.Member.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uUID_;
    /**
     * <pre>
     * 用户编号(OpenId)
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public java.lang.String getUUID() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uUID_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户编号(OpenId)
     * </pre>
     *
     * <code>string UUID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUUIDBytes() {
      java.lang.Object ref = uUID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uUID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 用户名
     * </pre>
     *
     * <code>string Name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEQUENCE_FIELD_NUMBER = 3;
    private int sequence_;
    /**
     * <pre>
     * 上线序列/染色(可选)
     * </pre>
     *
     * <code>fixed32 Sequence = 3;</code>
     */
    public int getSequence() {
      return sequence_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUUIDBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uUID_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (sequence_ != 0) {
        output.writeFixed32(3, sequence_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUUIDBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uUID_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (sequence_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, sequence_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reworld.www.Teamwork.Member)) {
        return super.equals(obj);
      }
      com.reworld.www.Teamwork.Member other = (com.reworld.www.Teamwork.Member) obj;

      if (!getUUID()
          .equals(other.getUUID())) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (getSequence()
          != other.getSequence()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUUID().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + getSequence();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reworld.www.Teamwork.Member parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Member parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Member parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Member parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reworld.www.Teamwork.Member prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Member}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Member)
        com.reworld.www.Teamwork.MemberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reworld.www.Teamwork.internal_static_Member_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reworld.www.Teamwork.internal_static_Member_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reworld.www.Teamwork.Member.class, com.reworld.www.Teamwork.Member.Builder.class);
      }

      // Construct using com.reworld.www.Teamwork.Member.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uUID_ = "";

        name_ = "";

        sequence_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reworld.www.Teamwork.internal_static_Member_descriptor;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Member getDefaultInstanceForType() {
        return com.reworld.www.Teamwork.Member.getDefaultInstance();
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Member build() {
        com.reworld.www.Teamwork.Member result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Member buildPartial() {
        com.reworld.www.Teamwork.Member result = new com.reworld.www.Teamwork.Member(this);
        result.uUID_ = uUID_;
        result.name_ = name_;
        result.sequence_ = sequence_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reworld.www.Teamwork.Member) {
          return mergeFrom((com.reworld.www.Teamwork.Member)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reworld.www.Teamwork.Member other) {
        if (other == com.reworld.www.Teamwork.Member.getDefaultInstance()) return this;
        if (!other.getUUID().isEmpty()) {
          uUID_ = other.uUID_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getSequence() != 0) {
          setSequence(other.getSequence());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reworld.www.Teamwork.Member parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reworld.www.Teamwork.Member) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uUID_ = "";
      /**
       * <pre>
       * 用户编号(OpenId)
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public java.lang.String getUUID() {
        java.lang.Object ref = uUID_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uUID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户编号(OpenId)
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUUIDBytes() {
        java.lang.Object ref = uUID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uUID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户编号(OpenId)
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uUID_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户编号(OpenId)
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder clearUUID() {
        
        uUID_ = getDefaultInstance().getUUID();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户编号(OpenId)
       * </pre>
       *
       * <code>string UUID = 1;</code>
       */
      public Builder setUUIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uUID_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 用户名
       * </pre>
       *
       * <code>string Name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int sequence_ ;
      /**
       * <pre>
       * 上线序列/染色(可选)
       * </pre>
       *
       * <code>fixed32 Sequence = 3;</code>
       */
      public int getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       * 上线序列/染色(可选)
       * </pre>
       *
       * <code>fixed32 Sequence = 3;</code>
       */
      public Builder setSequence(int value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 上线序列/染色(可选)
       * </pre>
       *
       * <code>fixed32 Sequence = 3;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Member)
    }

    // @@protoc_insertion_point(class_scope:Member)
    private static final com.reworld.www.Teamwork.Member DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reworld.www.Teamwork.Member();
    }

    public static com.reworld.www.Teamwork.Member getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Member>
        PARSER = new com.google.protobuf.AbstractParser<Member>() {
      @java.lang.Override
      public Member parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Member(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Member> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Member> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.reworld.www.Teamwork.Member getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>.PongCode Code = 1;</code>
     */
    int getCodeValue();
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>.PongCode Code = 1;</code>
     */
    com.reworld.www.Teamwork.PongCode getCode();

    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>.PongAction Action = 2;</code>
     */
    int getActionValue();
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>.PongAction Action = 2;</code>
     */
    com.reworld.www.Teamwork.PongAction getAction();

    /**
     * <pre>
     * 数据内容(可选),即透传数据包或Member对象
     * </pre>
     *
     * <code>bytes Data = 3;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * 响应
   * </pre>
   *
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      code_ = 0;
      action_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              code_ = rawValue;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              action_ = rawValue;
              break;
            }
            case 26: {

              data_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.reworld.www.Teamwork.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.reworld.www.Teamwork.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.reworld.www.Teamwork.Response.class, com.reworld.www.Teamwork.Response.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>.PongCode Code = 1;</code>
     */
    public int getCodeValue() {
      return code_;
    }
    /**
     * <pre>
     * 状态码
     * </pre>
     *
     * <code>.PongCode Code = 1;</code>
     */
    public com.reworld.www.Teamwork.PongCode getCode() {
      @SuppressWarnings("deprecation")
      com.reworld.www.Teamwork.PongCode result = com.reworld.www.Teamwork.PongCode.valueOf(code_);
      return result == null ? com.reworld.www.Teamwork.PongCode.UNRECOGNIZED : result;
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>.PongAction Action = 2;</code>
     */
    public int getActionValue() {
      return action_;
    }
    /**
     * <pre>
     * 操作类型
     * </pre>
     *
     * <code>.PongAction Action = 2;</code>
     */
    public com.reworld.www.Teamwork.PongAction getAction() {
      @SuppressWarnings("deprecation")
      com.reworld.www.Teamwork.PongAction result = com.reworld.www.Teamwork.PongAction.valueOf(action_);
      return result == null ? com.reworld.www.Teamwork.PongAction.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * 数据内容(可选),即透传数据包或Member对象
     * </pre>
     *
     * <code>bytes Data = 3;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != com.reworld.www.Teamwork.PongCode.ok.getNumber()) {
        output.writeEnum(1, code_);
      }
      if (action_ != com.reworld.www.Teamwork.PongAction.OnlineNotice.getNumber()) {
        output.writeEnum(2, action_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(3, data_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != com.reworld.www.Teamwork.PongCode.ok.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, code_);
      }
      if (action_ != com.reworld.www.Teamwork.PongAction.OnlineNotice.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.reworld.www.Teamwork.Response)) {
        return super.equals(obj);
      }
      com.reworld.www.Teamwork.Response other = (com.reworld.www.Teamwork.Response) obj;

      if (code_ != other.code_) return false;
      if (action_ != other.action_) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + code_;
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + action_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.reworld.www.Teamwork.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.reworld.www.Teamwork.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.reworld.www.Teamwork.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 响应
     * </pre>
     *
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        com.reworld.www.Teamwork.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.reworld.www.Teamwork.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.reworld.www.Teamwork.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.reworld.www.Teamwork.Response.class, com.reworld.www.Teamwork.Response.Builder.class);
      }

      // Construct using com.reworld.www.Teamwork.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        action_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.reworld.www.Teamwork.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Response getDefaultInstanceForType() {
        return com.reworld.www.Teamwork.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Response build() {
        com.reworld.www.Teamwork.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.reworld.www.Teamwork.Response buildPartial() {
        com.reworld.www.Teamwork.Response result = new com.reworld.www.Teamwork.Response(this);
        result.code_ = code_;
        result.action_ = action_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.reworld.www.Teamwork.Response) {
          return mergeFrom((com.reworld.www.Teamwork.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.reworld.www.Teamwork.Response other) {
        if (other == com.reworld.www.Teamwork.Response.getDefaultInstance()) return this;
        if (other.code_ != 0) {
          setCodeValue(other.getCodeValue());
        }
        if (other.action_ != 0) {
          setActionValue(other.getActionValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.reworld.www.Teamwork.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.reworld.www.Teamwork.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ = 0;
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>.PongCode Code = 1;</code>
       */
      public int getCodeValue() {
        return code_;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>.PongCode Code = 1;</code>
       */
      public Builder setCodeValue(int value) {
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>.PongCode Code = 1;</code>
       */
      public com.reworld.www.Teamwork.PongCode getCode() {
        @SuppressWarnings("deprecation")
        com.reworld.www.Teamwork.PongCode result = com.reworld.www.Teamwork.PongCode.valueOf(code_);
        return result == null ? com.reworld.www.Teamwork.PongCode.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>.PongCode Code = 1;</code>
       */
      public Builder setCode(com.reworld.www.Teamwork.PongCode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        code_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 状态码
       * </pre>
       *
       * <code>.PongCode Code = 1;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>.PongAction Action = 2;</code>
       */
      public int getActionValue() {
        return action_;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>.PongAction Action = 2;</code>
       */
      public Builder setActionValue(int value) {
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>.PongAction Action = 2;</code>
       */
      public com.reworld.www.Teamwork.PongAction getAction() {
        @SuppressWarnings("deprecation")
        com.reworld.www.Teamwork.PongAction result = com.reworld.www.Teamwork.PongAction.valueOf(action_);
        return result == null ? com.reworld.www.Teamwork.PongAction.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>.PongAction Action = 2;</code>
       */
      public Builder setAction(com.reworld.www.Teamwork.PongAction value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 操作类型
       * </pre>
       *
       * <code>.PongAction Action = 2;</code>
       */
      public Builder clearAction() {
        
        action_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 数据内容(可选),即透传数据包或Member对象
       * </pre>
       *
       * <code>bytes Data = 3;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * 数据内容(可选),即透传数据包或Member对象
       * </pre>
       *
       * <code>bytes Data = 3;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 数据内容(可选),即透传数据包或Member对象
       * </pre>
       *
       * <code>bytes Data = 3;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final com.reworld.www.Teamwork.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.reworld.www.Teamwork.Response();
    }

    public static com.reworld.www.Teamwork.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.reworld.www.Teamwork.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Member_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Member_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016response.proto\"6\n\006Member\022\014\n\004UUID\030\001 \001(\t" +
      "\022\014\n\004Name\030\002 \001(\t\022\020\n\010Sequence\030\003 \001(\007\"N\n\010Resp" +
      "onse\022\027\n\004Code\030\001 \001(\0162\t.PongCode\022\033\n\006Action\030" +
      "\002 \001(\0162\013.PongAction\022\014\n\004Data\030\003 \001(\014*}\n\nPong" +
      "Action\022\020\n\014OnlineNotice\020\000\022\021\n\rOfflineNotic" +
      "e\020\001\022\022\n\016DataDistribute\020\002\022\017\n\013DataReplica\020\003" +
      "\022\014\n\010Snapshot\020\004\022\n\n\006Hangup\020\005\022\013\n\007Dispose\020\006*" +
      "/\n\010PongCode\022\006\n\002ok\020\000\022\014\n\010err_sign\020\001\022\r\n\terr" +
      "_param\020\002B5\n\017com.reworld.wwwB\010TeamworkZ\005." +
      "/;pb\252\002\020Reworld.Teamworkb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Member_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Member_descriptor,
        new java.lang.String[] { "UUID", "Name", "Sequence", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Code", "Action", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
