// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: request222.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from request222.proto</summary>
public static partial class Request222Reflection {

  #region Descriptor
  /// <summary>File descriptor for request222.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static Request222Reflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChByZXF1ZXN0MjIyLnByb3RvIicKB1JlcXVlc3QSDgoGVGVhbUlkGAEgASgD",
          "EgwKBFVVSUQYAiABKAlCCVoHLjtrZWVwc2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Request), global::Request.Parser, new[]{ "TeamId", "UUID" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// 请求
/// </summary>
public sealed partial class Request : pb::IMessage<Request> {
  private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Request> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::Request222Reflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request(Request other) : this() {
    teamId_ = other.teamId_;
    uUID_ = other.uUID_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Request Clone() {
    return new Request(this);
  }

  /// <summary>Field number for the "TeamId" field.</summary>
  public const int TeamIdFieldNumber = 1;
  private long teamId_;
  /// <summary>
  /// 所在团队编号(必填)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public long TeamId {
    get { return teamId_; }
    set {
      teamId_ = value;
    }
  }

  /// <summary>Field number for the "UUID" field.</summary>
  public const int UUIDFieldNumber = 2;
  private string uUID_ = "";
  /// <summary>
  /// 用户编号(必填)
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string UUID {
    get { return uUID_; }
    set {
      uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Request);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Request other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (TeamId != other.TeamId) return false;
    if (UUID != other.UUID) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (TeamId != 0L) hash ^= TeamId.GetHashCode();
    if (UUID.Length != 0) hash ^= UUID.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (TeamId != 0L) {
      output.WriteRawTag(8);
      output.WriteInt64(TeamId);
    }
    if (UUID.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(UUID);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (TeamId != 0L) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamId);
    }
    if (UUID.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Request other) {
    if (other == null) {
      return;
    }
    if (other.TeamId != 0L) {
      TeamId = other.TeamId;
    }
    if (other.UUID.Length != 0) {
      UUID = other.UUID;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          TeamId = input.ReadInt64();
          break;
        }
        case 18: {
          UUID = input.ReadString();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
