// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: response.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Reworld.Teamwork {

  /// <summary>Holder for reflection information generated from response.proto</summary>
  public static partial class ResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for response.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5yZXNwb25zZS5wcm90byI2CgZNZW1iZXISDAoEVVVJRBgBIAEoCRIMCgRO",
            "YW1lGAIgASgJEhAKCFNlcXVlbmNlGAMgASgHIk4KCFJlc3BvbnNlEhcKBENv",
            "ZGUYASABKA4yCS5Qb25nQ29kZRIbCgZBY3Rpb24YAiABKA4yCy5Qb25nQWN0",
            "aW9uEgwKBERhdGEYAyABKAwqfQoKUG9uZ0FjdGlvbhIQCgxPbmxpbmVOb3Rp",
            "Y2UQABIRCg1PZmZsaW5lTm90aWNlEAESEgoORGF0YURpc3RyaWJ1dGUQAhIP",
            "CgtEYXRhUmVwbGljYRADEgwKCFNuYXBzaG90EAQSCgoGSGFuZ3VwEAUSCwoH",
            "RGlzcG9zZRAGKi8KCFBvbmdDb2RlEgYKAm9rEAASDAoIZXJyX3NpZ24QARIN",
            "CgllcnJfcGFyYW0QAkI1Cg9jb20ucmV3b3JsZC53d3dCCFRlYW13b3JrWgUu",
            "LztwYqoCEFJld29ybGQuVGVhbXdvcmtiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Reworld.Teamwork.PongAction), typeof(global::Reworld.Teamwork.PongCode), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Reworld.Teamwork.Member), global::Reworld.Teamwork.Member.Parser, new[]{ "UUID", "Name", "Sequence" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Reworld.Teamwork.Response), global::Reworld.Teamwork.Response.Parser, new[]{ "Code", "Action", "Data" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 服务端响应操作类型
  /// </summary>
  public enum PongAction {
    /// <summary>
    /// 成员上线通知(带有染色等状态数据)
    /// </summary>
    [pbr::OriginalName("OnlineNotice")] OnlineNotice = 0,
    /// <summary>
    /// 成员(主动)下线通知
    /// </summary>
    [pbr::OriginalName("OfflineNotice")] OfflineNotice = 1,
    /// <summary>
    /// 地图分发数据(透传) packet
    /// </summary>
    [pbr::OriginalName("DataDistribute")] DataDistribute = 2,
    /// <summary>
    /// 地图副本数据(透传)
    /// </summary>
    [pbr::OriginalName("DataReplica")] DataReplica = 3,
    /// <summary>
    /// 请求定时快照
    /// </summary>
    [pbr::OriginalName("Snapshot")] Snapshot = 4,
    /// <summary>
    /// 暂停编辑(通知)
    /// </summary>
    [pbr::OriginalName("Hangup")] Hangup = 5,
    /// <summary>
    /// 销毁项目(通知)
    /// </summary>
    [pbr::OriginalName("Dispose")] Dispose = 6,
  }

  public enum PongCode {
    /// <summary>
    /// 正常
    /// </summary>
    [pbr::OriginalName("ok")] Ok = 0,
    /// <summary>
    /// 签名错误
    /// </summary>
    [pbr::OriginalName("err_sign")] ErrSign = 1,
    /// <summary>
    /// 参数错误
    /// </summary>
    [pbr::OriginalName("err_param")] ErrParam = 2,
  }

  #endregion

  #region Messages
  public sealed partial class Member : pb::IMessage<Member> {
    private static readonly pb::MessageParser<Member> _parser = new pb::MessageParser<Member>(() => new Member());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Member> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reworld.Teamwork.ResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member(Member other) : this() {
      uUID_ = other.uUID_;
      name_ = other.name_;
      sequence_ = other.sequence_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Member Clone() {
      return new Member(this);
    }

    /// <summary>Field number for the "UUID" field.</summary>
    public const int UUIDFieldNumber = 1;
    private string uUID_ = "";
    /// <summary>
    /// 用户编号(OpenId)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string UUID {
      get { return uUID_; }
      set {
        uUID_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    /// <summary>
    /// 用户名
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Sequence" field.</summary>
    public const int SequenceFieldNumber = 3;
    private uint sequence_;
    /// <summary>
    /// 上线序列/染色(可选)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Sequence {
      get { return sequence_; }
      set {
        sequence_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Member);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Member other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UUID != other.UUID) return false;
      if (Name != other.Name) return false;
      if (Sequence != other.Sequence) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (UUID.Length != 0) hash ^= UUID.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Sequence != 0) hash ^= Sequence.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (UUID.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(UUID);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (Sequence != 0) {
        output.WriteRawTag(29);
        output.WriteFixed32(Sequence);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (UUID.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UUID);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Sequence != 0) {
        size += 1 + 4;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Member other) {
      if (other == null) {
        return;
      }
      if (other.UUID.Length != 0) {
        UUID = other.UUID;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Sequence != 0) {
        Sequence = other.Sequence;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            UUID = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 29: {
            Sequence = input.ReadFixed32();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// 响应
  /// </summary>
  public sealed partial class Response : pb::IMessage<Response> {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Reworld.Teamwork.ResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response(Response other) : this() {
      code_ = other.code_;
      action_ = other.action_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "Code" field.</summary>
    public const int CodeFieldNumber = 1;
    private global::Reworld.Teamwork.PongCode code_ = global::Reworld.Teamwork.PongCode.Ok;
    /// <summary>
    /// 状态码
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reworld.Teamwork.PongCode Code {
      get { return code_; }
      set {
        code_ = value;
      }
    }

    /// <summary>Field number for the "Action" field.</summary>
    public const int ActionFieldNumber = 2;
    private global::Reworld.Teamwork.PongAction action_ = global::Reworld.Teamwork.PongAction.OnlineNotice;
    /// <summary>
    /// 操作类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Reworld.Teamwork.PongAction Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    /// <summary>Field number for the "Data" field.</summary>
    public const int DataFieldNumber = 3;
    private pb::ByteString data_ = pb::ByteString.Empty;
    /// <summary>
    /// 数据内容(可选),即透传数据包或Member对象
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Code != other.Code) return false;
      if (Action != other.Action) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Code != global::Reworld.Teamwork.PongCode.Ok) hash ^= Code.GetHashCode();
      if (Action != global::Reworld.Teamwork.PongAction.OnlineNotice) hash ^= Action.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Code != global::Reworld.Teamwork.PongCode.Ok) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Code);
      }
      if (Action != global::Reworld.Teamwork.PongAction.OnlineNotice) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Action);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Code != global::Reworld.Teamwork.PongCode.Ok) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Code);
      }
      if (Action != global::Reworld.Teamwork.PongAction.OnlineNotice) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Action);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Code != global::Reworld.Teamwork.PongCode.Ok) {
        Code = other.Code;
      }
      if (other.Action != global::Reworld.Teamwork.PongAction.OnlineNotice) {
        Action = other.Action;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Code = (global::Reworld.Teamwork.PongCode) input.ReadEnum();
            break;
          }
          case 16: {
            Action = (global::Reworld.Teamwork.PongAction) input.ReadEnum();
            break;
          }
          case 26: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
