<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Member</code>
 */
class Member extends \Google\Protobuf\Internal\Message
{
    /**
     * 用户编号(OpenId)
     *
     * Generated from protobuf field <code>string UUID = 1;</code>
     */
    private $UUID = '';
    /**
     * 用户名
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    private $Name = '';
    /**
     * 上线序列/染色(可选)
     *
     * Generated from protobuf field <code>fixed32 Sequence = 3;</code>
     */
    private $Sequence = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UUID
     *           用户编号(OpenId)
     *     @type string $Name
     *           用户名
     *     @type int $Sequence
     *           上线序列/染色(可选)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * 用户编号(OpenId)
     *
     * Generated from protobuf field <code>string UUID = 1;</code>
     * @return string
     */
    public function getUUID()
    {
        return $this->UUID;
    }

    /**
     * 用户编号(OpenId)
     *
     * Generated from protobuf field <code>string UUID = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->UUID = $var;

        return $this;
    }

    /**
     * 用户名
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * 用户名
     *
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * 上线序列/染色(可选)
     *
     * Generated from protobuf field <code>fixed32 Sequence = 3;</code>
     * @return int
     */
    public function getSequence()
    {
        return $this->Sequence;
    }

    /**
     * 上线序列/染色(可选)
     *
     * Generated from protobuf field <code>fixed32 Sequence = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setSequence($var)
    {
        GPBUtil::checkUint32($var);
        $this->Sequence = $var;

        return $this;
    }

}

