<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

if (false) {
    /**
     * This class is deprecated. Use PersonReply\Sex instead.
     * @deprecated
     */
    class PersonReply_Sex {}
}
class_exists(PersonReply\Sex::class);
@trigger_error('PersonReply_Sex is deprecated and will be removed in the next major release. Use PersonReply\Sex instead', E_USER_DEPRECATED);

