<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

/**
 * Protobuf type <code>PongCode</code>
 */
class PongCode
{
    /**
     * 正常
     *
     * Generated from protobuf enum <code>ok = 0;</code>
     */
    const ok = 0;
    /**
     * 签名错误
     *
     * Generated from protobuf enum <code>err_sign = 1;</code>
     */
    const err_sign = 1;
    /**
     * 参数错误
     *
     * Generated from protobuf enum <code>err_param = 2;</code>
     */
    const err_param = 2;

    private static $valueToName = [
        self::ok => 'ok',
        self::err_sign => 'err_sign',
        self::err_param => 'err_param',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

