<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request222.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 请求
 *
 * Generated from protobuf message <code>Request</code>
 */
class Request extends \Google\Protobuf\Internal\Message
{
    /**
     * 所在团队编号(必填)
     *
     * Generated from protobuf field <code>int64 TeamId = 1;</code>
     */
    private $TeamId = 0;
    /**
     * 用户编号(必填)
     *
     * Generated from protobuf field <code>string UUID = 2;</code>
     */
    private $UUID = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int|string $TeamId
     *           所在团队编号(必填)
     *     @type string $UUID
     *           用户编号(必填)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Request222::initOnce();
        parent::__construct($data);
    }

    /**
     * 所在团队编号(必填)
     *
     * Generated from protobuf field <code>int64 TeamId = 1;</code>
     * @return int|string
     */
    public function getTeamId()
    {
        return $this->TeamId;
    }

    /**
     * 所在团队编号(必填)
     *
     * Generated from protobuf field <code>int64 TeamId = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTeamId($var)
    {
        GPBUtil::checkInt64($var);
        $this->TeamId = $var;

        return $this;
    }

    /**
     * 用户编号(必填)
     *
     * Generated from protobuf field <code>string UUID = 2;</code>
     * @return string
     */
    public function getUUID()
    {
        return $this->UUID;
    }

    /**
     * 用户编号(必填)
     *
     * Generated from protobuf field <code>string UUID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setUUID($var)
    {
        GPBUtil::checkString($var, True);
        $this->UUID = $var;

        return $this;
    }

}

