<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 响应
 *
 * Generated from protobuf message <code>Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     * 状态码
     *
     * Generated from protobuf field <code>.PongCode Code = 1;</code>
     */
    private $Code = 0;
    /**
     * 操作类型
     *
     * Generated from protobuf field <code>.PongAction Action = 2;</code>
     */
    private $Action = 0;
    /**
     * 数据内容(可选),即透传数据包或Member对象
     *
     * Generated from protobuf field <code>bytes Data = 3;</code>
     */
    private $Data = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Code
     *           状态码
     *     @type int $Action
     *           操作类型
     *     @type string $Data
     *           数据内容(可选),即透传数据包或Member对象
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     * 状态码
     *
     * Generated from protobuf field <code>.PongCode Code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->Code;
    }

    /**
     * 状态码
     *
     * Generated from protobuf field <code>.PongCode Code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkEnum($var, \PongCode::class);
        $this->Code = $var;

        return $this;
    }

    /**
     * 操作类型
     *
     * Generated from protobuf field <code>.PongAction Action = 2;</code>
     * @return int
     */
    public function getAction()
    {
        return $this->Action;
    }

    /**
     * 操作类型
     *
     * Generated from protobuf field <code>.PongAction Action = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAction($var)
    {
        GPBUtil::checkEnum($var, \PongAction::class);
        $this->Action = $var;

        return $this;
    }

    /**
     * 数据内容(可选),即透传数据包或Member对象
     *
     * Generated from protobuf field <code>bytes Data = 3;</code>
     * @return string
     */
    public function getData()
    {
        return $this->Data;
    }

    /**
     * 数据内容(可选),即透传数据包或Member对象
     *
     * Generated from protobuf field <code>bytes Data = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, False);
        $this->Data = $var;

        return $this;
    }

}

