<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request222.proto

namespace GPBMetadata;

class Request222
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4e0a10726571756573743232322e70726f746f22270a07526571756573" .
            "74120e0a065465616d4964180120012803120c0a04555549441802200128" .
            "0942095a072e3b6b65657073620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

