<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

namespace GPBMetadata;

class Request
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa2020a0d726571756573742e70726f746f2285010a0752657175657374" .
            "121b0a06416374696f6e18012001280e320b2e50696e67416374696f6e12" .
            "0e0a065465616d4964180220012803120c0a045555494418032001280912" .
            "110a0954696d657374616d70180420012803120c0a045369676e18052001" .
            "280912100a087265636569766572180620032809120c0a04446174611807" .
            "2001280c2a4b0a0a50696e67416374696f6e120d0a094865617274626561" .
            "741000120e0a0a5265715265706c696361100112110a0d52657144697374" .
            "7269627574651002120b0a074f66666c696e65100342340a0f636f6d2e72" .
            "65776f726c642e77777742085465616d776f726b5a042e3b7062aa021052" .
            "65776f726c642e5465616d776f726b620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

