<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

namespace GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a87030a0e726573706f6e73652e70726f746f22360a064d656d62657212" .
            "0c0a0455554944180120012809120c0a044e616d6518022001280912100a" .
            "0853657175656e6365180320012807224e0a08526573706f6e736512170a" .
            "04436f646518012001280e32092e506f6e67436f6465121b0a0641637469" .
            "6f6e18022001280e320b2e506f6e67416374696f6e120c0a044461746118" .
            "032001280c2a7d0a0a506f6e67416374696f6e12100a0c4f6e6c696e654e" .
            "6f74696365100012110a0d4f66666c696e654e6f74696365100112120a0e" .
            "44617461446973747269627574651002120f0a0b446174615265706c6963" .
            "611003120c0a08536e617073686f741004120a0a0648616e677570100512" .
            "0b0a07446973706f736510062a2f0a08506f6e67436f646512060a026f6b" .
            "1000120c0a086572725f7369676e1001120d0a096572725f706172616d10" .
            "0242350a0f636f6d2e7265776f726c642e77777742085465616d776f726b" .
            "5a052e2f3b7062aa02105265776f726c642e5465616d776f726b62067072" .
            "6f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

