# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from include.google.protobuf import any_pb2 as include_dot_google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\017com.reworld.wwwB\010TeamworkZ\004.;pb\252\002\020Reworld.Teamwork'),
  serialized_pb=_b('\n\x0eprotocol.proto\x1a!include/google/protobuf/any.proto\"\xdb\x01\n\x0bPersonReply\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07id_card\x18\x02 \x01(\t\x12\x0b\n\x03\x61ge\x18\x03 \x01(\x05\x12\x1d\n\x03sex\x18\x04 \x01(\x0e\x32\x10.PersonReply.Sex\x12\x0f\n\x07married\x18\x05 \x01(\x08\x12\x0e\n\x06\x61mount\x18\x06 \x01(\x01\x12\x0f\n\x07\x61\x64\x64ress\x18\x07 \x03(\t\x12$\n\x06Others\x18\t \x03(\x0b\x32\x14.google.protobuf.Any\x12\x0c\n\x04\x64\x61ta\x18\n \x01(\x0c\"\x1b\n\x03Sex\x12\n\n\x06\x46\x45MALE\x10\x00\x12\x08\n\x04MALE\x10\x01\x42\x34\n\x0f\x63om.reworld.wwwB\x08TeamworkZ\x04.;pb\xaa\x02\x10Reworld.Teamworkb\x06proto3')
  ,
  dependencies=[include_dot_google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])



_PERSONREPLY_SEX = _descriptor.EnumDescriptor(
  name='Sex',
  full_name='PersonReply.Sex',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FEMALE', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MALE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=246,
  serialized_end=273,
)
_sym_db.RegisterEnumDescriptor(_PERSONREPLY_SEX)


_PERSONREPLY = _descriptor.Descriptor(
  name='PersonReply',
  full_name='PersonReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='PersonReply.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id_card', full_name='PersonReply.id_card', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='age', full_name='PersonReply.age', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sex', full_name='PersonReply.sex', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='married', full_name='PersonReply.married', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='amount', full_name='PersonReply.amount', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='address', full_name='PersonReply.address', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Others', full_name='PersonReply.Others', index=7,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='PersonReply.data', index=8,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PERSONREPLY_SEX,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=273,
)

_PERSONREPLY.fields_by_name['sex'].enum_type = _PERSONREPLY_SEX
_PERSONREPLY.fields_by_name['Others'].message_type = include_dot_google_dot_protobuf_dot_any__pb2._ANY
_PERSONREPLY_SEX.containing_type = _PERSONREPLY
DESCRIPTOR.message_types_by_name['PersonReply'] = _PERSONREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonReply = _reflection.GeneratedProtocolMessageType('PersonReply', (_message.Message,), {
  'DESCRIPTOR' : _PERSONREPLY,
  '__module__' : 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:PersonReply)
  })
_sym_db.RegisterMessage(PersonReply)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
