# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='response.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\017com.reworld.wwwB\010TeamworkZ\005./;pb\252\002\020Reworld.Teamwork'),
  serialized_pb=_b('\n\x0eresponse.proto\"6\n\x06Member\x12\x0c\n\x04UUID\x18\x01 \x01(\t\x12\x0c\n\x04Name\x18\x02 \x01(\t\x12\x10\n\x08Sequence\x18\x03 \x01(\x07\"N\n\x08Response\x12\x17\n\x04\x43ode\x18\x01 \x01(\x0e\x32\t.PongCode\x12\x1b\n\x06\x41\x63tion\x18\x02 \x01(\x0e\x32\x0b.PongAction\x12\x0c\n\x04\x44\x61ta\x18\x03 \x01(\x0c*}\n\nPongAction\x12\x10\n\x0cOnlineNotice\x10\x00\x12\x11\n\rOfflineNotice\x10\x01\x12\x12\n\x0e\x44\x61taDistribute\x10\x02\x12\x0f\n\x0b\x44\x61taReplica\x10\x03\x12\x0c\n\x08Snapshot\x10\x04\x12\n\n\x06Hangup\x10\x05\x12\x0b\n\x07\x44ispose\x10\x06*/\n\x08PongCode\x12\x06\n\x02ok\x10\x00\x12\x0c\n\x08\x65rr_sign\x10\x01\x12\r\n\terr_param\x10\x02\x42\x35\n\x0f\x63om.reworld.wwwB\x08TeamworkZ\x05./;pb\xaa\x02\x10Reworld.Teamworkb\x06proto3')
)

_PONGACTION = _descriptor.EnumDescriptor(
  name='PongAction',
  full_name='PongAction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OnlineNotice', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OfflineNotice', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DataDistribute', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DataReplica', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Snapshot', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Hangup', index=5, number=5,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Dispose', index=6, number=6,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=154,
  serialized_end=279,
)
_sym_db.RegisterEnumDescriptor(_PONGACTION)

PongAction = enum_type_wrapper.EnumTypeWrapper(_PONGACTION)
_PONGCODE = _descriptor.EnumDescriptor(
  name='PongCode',
  full_name='PongCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ok', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='err_sign', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='err_param', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=281,
  serialized_end=328,
)
_sym_db.RegisterEnumDescriptor(_PONGCODE)

PongCode = enum_type_wrapper.EnumTypeWrapper(_PONGCODE)
OnlineNotice = 0
OfflineNotice = 1
DataDistribute = 2
DataReplica = 3
Snapshot = 4
Hangup = 5
Dispose = 6
ok = 0
err_sign = 1
err_param = 2



_MEMBER = _descriptor.Descriptor(
  name='Member',
  full_name='Member',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='UUID', full_name='Member.UUID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Name', full_name='Member.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Sequence', full_name='Member.Sequence', index=2,
      number=3, type=7, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=72,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='Response.Code', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Action', full_name='Response.Action', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='Response.Data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=152,
)

_RESPONSE.fields_by_name['Code'].enum_type = _PONGCODE
_RESPONSE.fields_by_name['Action'].enum_type = _PONGACTION
DESCRIPTOR.message_types_by_name['Member'] = _MEMBER
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['PongAction'] = _PONGACTION
DESCRIPTOR.enum_types_by_name['PongCode'] = _PONGCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Member = _reflection.GeneratedProtocolMessageType('Member', (_message.Message,), {
  'DESCRIPTOR' : _MEMBER,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:Member)
  })
_sym_db.RegisterMessage(Member)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'response_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
