// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request222.proto

package keeps

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求
type Request struct {
	// 所在团队编号(必填)
	TeamId int64 `protobuf:"varint,1,opt,name=TeamId,proto3" json:"TeamId,omitempty"`
	// 用户编号(必填)
	UUID                 string   `protobuf:"bytes,2,opt,name=UUID,proto3" json:"UUID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_b662a4fbf8eccb37, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Request) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "Request")
}

func init() { proto.RegisterFile("request222.proto", fileDescriptor_b662a4fbf8eccb37) }

var fileDescriptor_b662a4fbf8eccb37 = []byte{
	// 101 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0x31, 0x32, 0x32, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe5, 0x62,
	0x0f, 0x82, 0x88, 0x09, 0x89, 0x71, 0xb1, 0x85, 0xa4, 0x26, 0xe6, 0x7a, 0xa6, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x30, 0x07, 0x41, 0x79, 0x42, 0x42, 0x5c, 0x2c, 0xa1, 0xa1, 0x9e, 0x2e, 0x12, 0x4c,
	0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x13, 0x67, 0x14, 0xbb, 0x9e, 0x75, 0x76, 0x6a, 0x6a,
	0x41, 0x71, 0x12, 0x1b, 0xd8, 0x20, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x42, 0x6e, 0x1a,
	0x71, 0x5c, 0x00, 0x00, 0x00,
}
