// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 客户端请求操作类型
type PingAction int32

const (
	// 心跳
	PingAction_Heartbeat PingAction = 0
	// 请求地图副本
	PingAction_ReqReplica PingAction = 1
	// 请求分发数据(副本/动作)
	PingAction_ReqDistribute PingAction = 2
	// 通知下线
	PingAction_Offline PingAction = 3
)

var PingAction_name = map[int32]string{
	0: "Heartbeat",
	1: "ReqReplica",
	2: "ReqDistribute",
	3: "Offline",
}

var PingAction_value = map[string]int32{
	"Heartbeat":     0,
	"ReqReplica":    1,
	"ReqDistribute": 2,
	"Offline":       3,
}

func (x PingAction) String() string {
	return proto.EnumName(PingAction_name, int32(x))
}

func (PingAction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

// 请求
type Request struct {
	// 操作类型(必填)
	Action PingAction `protobuf:"varint,1,opt,name=Action,proto3,enum=PingAction" json:"Action,omitempty"`
	// 所在团队编号(必填)
	TeamId int64 `protobuf:"varint,2,opt,name=TeamId,proto3" json:"TeamId,omitempty"`
	// 用户编号(必填)
	UUID string `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	// 时间戳(必填)
	Timestamp int64 `protobuf:"varint,4,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	// 签名(必填)(算法：sha256(TeamId.UUID.Timestamp.Secret))
	Sign string `protobuf:"bytes,5,opt,name=Sign,proto3" json:"Sign,omitempty"`
	// 接收者(可选,为空时群发)
	Receiver []string `protobuf:"bytes,6,rep,name=receiver,proto3" json:"receiver,omitempty"`
	// 数据内容(可选)
	Data                 []byte   `protobuf:"bytes,7,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAction() PingAction {
	if m != nil {
		return m.Action
	}
	return PingAction_Heartbeat
}

func (m *Request) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *Request) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *Request) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Request) GetSign() string {
	if m != nil {
		return m.Sign
	}
	return ""
}

func (m *Request) GetReceiver() []string {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("PingAction", PingAction_name, PingAction_value)
	proto.RegisterType((*Request)(nil), "Request")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0x3f, 0x27, 0xf9, 0x92, 0xe6, 0x96, 0x94, 0xe0, 0x01, 0x59, 0x88, 0x21, 0x82, 0x25,
	0x62, 0xc8, 0x00, 0x6c, 0x4c, 0x54, 0x19, 0xa8, 0x18, 0x40, 0xa6, 0x5d, 0xd8, 0x9c, 0xf4, 0xb6,
	0xb2, 0x48, 0xe2, 0xc4, 0x71, 0xc9, 0x3b, 0xf1, 0x0c, 0x3c, 0x1c, 0xca, 0x1f, 0xe8, 0x76, 0xce,
	0xf9, 0x9d, 0x23, 0xd9, 0x17, 0x02, 0x8d, 0xcd, 0x01, 0x5b, 0x93, 0xd4, 0x5a, 0x19, 0x75, 0xf5,
	0x4d, 0xc0, 0xe3, 0x63, 0x42, 0xaf, 0xc1, 0x7d, 0xcc, 0x8d, 0x54, 0x15, 0x23, 0x11, 0x89, 0x17,
	0xb7, 0xf3, 0xe4, 0x55, 0x56, 0xfb, 0x31, 0xe2, 0x13, 0xa2, 0xe7, 0xe0, 0xae, 0x51, 0x94, 0xab,
	0x2d, 0xb3, 0x22, 0x12, 0xdb, 0x7c, 0x72, 0x94, 0x82, 0xb3, 0xd9, 0xac, 0x52, 0x66, 0x47, 0x24,
	0xf6, 0xf9, 0xa0, 0xe9, 0x25, 0xf8, 0x6b, 0x59, 0x62, 0x6b, 0x44, 0x59, 0x33, 0x67, 0xa8, 0x1f,
	0x83, 0x7e, 0xf1, 0x26, 0xf7, 0x15, 0xfb, 0x3f, 0x2e, 0x7a, 0x4d, 0x2f, 0x60, 0xa6, 0x31, 0x47,
	0xf9, 0x89, 0x9a, 0xb9, 0x91, 0x1d, 0xfb, 0xfc, 0xcf, 0xf7, 0xfd, 0x54, 0x18, 0xc1, 0xbc, 0x88,
	0xc4, 0x27, 0x7c, 0xd0, 0x37, 0xcf, 0x00, 0xc7, 0x37, 0xd2, 0x00, 0xfc, 0x27, 0x14, 0xda, 0x64,
	0x28, 0x4c, 0xf8, 0x8f, 0x2e, 0x00, 0x38, 0x36, 0x1c, 0xeb, 0x42, 0xe6, 0x22, 0x24, 0xf4, 0x0c,
	0x02, 0x8e, 0x4d, 0x2a, 0x5b, 0xa3, 0x65, 0x76, 0x30, 0x18, 0x5a, 0x74, 0x0e, 0xde, 0xcb, 0x6e,
	0x57, 0xc8, 0x0a, 0x43, 0x7b, 0x79, 0x0f, 0xa7, 0xb9, 0x2a, 0x13, 0x8d, 0x9d, 0xd2, 0xc5, 0x36,
	0xe9, 0xba, 0x6e, 0x39, 0xeb, 0x7f, 0xd7, 0x29, 0xfd, 0xf1, 0xee, 0x24, 0x0f, 0x75, 0xf6, 0x65,
	0x85, 0x7c, 0xa2, 0xbf, 0x20, 0x73, 0x87, 0x43, 0xde, 0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0x19,
	0x2f, 0xc1, 0x01, 0x59, 0x01, 0x00, 0x00,
}
